language: python
python:
  - "2.7"
  - "3.2"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-lxml
  - sudo apt-get install -qq python3-scipy python3-lxml
  - git clone https://lorenz_l@bitbucket.org/mozman/ezdxf
  - sudo pip install -e ezdxf
install:
  - pip install -r requires.txt
  - pip install coveralls
script:
  - python testall.py
  - coverage run testall.py
after_success:
  - coveralls
branches:
  only:
    - master
    - develop