dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython python-scipy python-lxml
  - sudo apt-get install -qq cython3 python3-scipy python3-lxml
  - sudo apt-get install -qq hgsubversion
install:
  - hg clone https://bitbucket.org/anantha_ani/ezdxf-mozman
  - sudo pip install -e ezdxf-mozman
  - pip install -r requires.txt
  - pip install coveralls
script:
  - python testall.py
  - coverage run testall.py
after_success:
  - coveralls
branches:
  only:
    - master
    - develop