sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    sources:
      - python-scipy
      - python3-scipy
      - hgsubversion
install:
  - pip install -r requires.txt
  - pip install coveralls
script:
  - python testall.py
  - coverage run testall.py
after_success:
  - coveralls
branches:
  only:
    - master
    - develop