language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-lxml
install:
  - pip install -r requires.txt
script: python testall.py
branches:
  only:
    - master
