package:
  name: openglider
  version: 0.0.1

build:
  number: 1

source:
  path: ../../

requirements:
  build:
    - python
    - meshpy
    - parabem
    - numpy
    - ezodf
    - lxml
    - ezdxf
    - svgwrite
  run:                    #   channels
    - python
    - meshpy              #   - https://conda.anaconda.org/looooo
    - parabem             #   - https://conda.anaconda.org/looooo
    - numpy
    - ezodf               #   - https://conda.anaconda.org/looooo
    - svgwrite            #   - https://conda.anaconda.org/omnia
    - ezdxf               #   - https://conda.anaconda.org/looooo
    - lxml                #   - https://conda.anaconda.org/anaconda

about:
  summary: paraglider design